import { Session } from "../types";
import { SessionStore } from "../stores/sessionStore";

const sessionStore = new SessionStore();

// Mostly generated by ChatGPT
export const getSession = (id: string): Session | undefined => {
  return sessionStore.findSession(id);
};

export const saveSession = (id: string, session: Session): void => {
  sessionStore.saveSession(id, session);
};

export const getAllSessions = (): Session[] => {
  return sessionStore.findAllSessions();
};

export const getSessionByUsername = (username: string): Session | undefined => {
  return sessionStore.findSessionByUsername(username);
};
